GET http://localhost:3000/comments HTTP/1.1

###

GET http://localhost:3000/comments/?parentId=x652b2a3576d85c632249e24b HTTP/1.1

###

POST http://localhost:3000/comments HTTP/1.1
content-type: application/json

{
    "text": "nested comment inside the third comment by another user",
    "userId": "652b231f226e4aa2ce1df5e9",
    "parentId": "652b2a3576d85c632249e24b"
}

# {
#     "name": 6,
# }